from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse


AUTH_ROOT = Path(".auth")


@dataclass(frozen=True)
class SiteAuth:
    key: str
    name: str
    login_url: str
    match_hosts: tuple[str, ...]


SITES = {
    "bilibili": SiteAuth(
        key="bilibili",
        name="B站",
        login_url="https://www.bilibili.com/",
        match_hosts=("bilibili.com", "b23.tv"),
    ),
    "youtube": SiteAuth(
        key="youtube",
        name="YouTube",
        login_url="https://www.youtube.com/",
        match_hosts=("youtube.com", "youtu.be", "google.com"),
    ),
}


def auth_profile_dir(site_key: str) -> Path:
    return AUTH_ROOT / "browser-profiles" / site_key


def cookie_file_path(site_key: str) -> Path:
    return AUTH_ROOT / "cookies" / f"{site_key}.cookies.txt"


def detect_site(url: str) -> SiteAuth | None:
    host = urlparse(url).hostname or ""
    host = host.lower()
    for site in SITES.values():
        if any(host == match_host or host.endswith(f".{match_host}") for match_host in site.match_hosts):
            return site
    return None


def get_site(site_key: str) -> SiteAuth:
    if site_key not in SITES:
        supported = ", ".join(SITES)
        raise ValueError(f"不支持的网站：{site_key}。当前支持：{supported}")
    return SITES[site_key]


def write_netscape_cookie_file(cookies: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by subtitle-fetcher. Keep it private.",
        "",
    ]
    for cookie in cookies:
        domain = cookie.get("domain") or ""
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path_value = cookie.get("path") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = int(cookie.get("expires") or 0)
        if expires < 0:
            expires = 0
        name = cookie.get("name") or ""
        value = cookie.get("value") or ""
        if not domain or not name:
            continue
        lines.append("\t".join([domain, include_subdomains, path_value, secure, str(expires), name, value]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
